AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  pi-app-api
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    MemorySize: 1028

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON

Resources:
  FrontendBucket:    
    Type: AWS::S3::Bucket
    Properties:
      BucketName: pi-app-ui

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: FrontendBucket
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}"
          - Id: Backend
            DomainName: !Sub "${ApiGatewayEndpoint}.execute-api.${AWS::Region}.amazonaws.com"
            OriginPath: "/Prod"
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          TargetOriginId: FrontendBucket
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: true
        CacheBehaviors:
          - TargetOriginId: Backend
            PathPattern: "api/*"
            DefaultTTL: 0
            MinTTL: 0
            MaxTTL: 0
            ViewerProtocolPolicy: https-only
            AllowedMethods: [GET,HEAD,OPTIONS,PUT,PATCH,POST,DELETE]
            ForwardedValues:
              QueryString: true
        CustomErrorResponses:
          - ErrorCode: '404'
            ResponsePagePath: "/index.html"
            ResponseCode: '200'
            ErrorCachingMinTTL: '30'
          - ErrorCode: '403'
            ResponsePagePath: "/index.html"
            ResponseCode: '200'
            ErrorCachingMinTTL: '30'
        Enabled: true
        DefaultRootObject: index.html
        

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: 
              CanonicalUser: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId
            Action: 's3:GetObject'
            Resource: !Sub
              - 'arn:aws:s3:::${Bucket}/*'
              - Bucket: !Ref FrontendBucket
      Bucket: !Ref FrontendBucket
          
  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties: 
      CloudFrontOriginAccessIdentityConfig: 
        Comment: CloudFront access identity   


  # Build the API Gateway 

  ApiGatewayEndpoint:
    Type: "AWS::Serverless::Api"
    Properties:
      StageName: Prod
      Auth:
        ApiKeyRequired: false
      

  PiAppApiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: api/
      Handler: handler.lambda_handler
      Runtime: python3.12
      Timeout: 60

      Architectures:
        - x86_64
      Policies:
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          OPEN_WEATHER_API_KEY: !Ref OpenWeatherApiKey
          OPENAI_API_KEY: !Ref OpenAIApiKey
          WMATA_API_KEY: !Ref MetroApiKey
          ALBUM_REVIEW_TABLE_NAME: music_reviews
          GOOGLE_CLIENT_ID:  !Ref GoogleClientId
          GOOGLE_CLIENT_SECRET:  !Ref GoogleClientSecret
          GOOGLE_REFRESH_TOKEN: !Ref GoogleRefreshToken
          HOME_ASSISTANT_HOST: !Ref HomeAssistantHost
          HOME_ASSISTANT_TOKEN: !Ref HomeAssistantToken

          ENV: PROD
      Events:
        HttpApiAnyPathAnyMethod:
          # Wildcard all Paths and Methods (does not include "/")
          Type: Api
          Properties:
            RestApiId:
              Ref: ApiGatewayEndpoint
            Path: /{proxy+}
            Method: any      
Parameters:
  OpenWeatherApiKey:
    Type: String
    Default: ""
    NoEcho: true
  MetroApiKey:
    Type: String
    Default: ""
    NoEcho: true
  GoogleClientId:
    Type: String
    Default: ""
    NoEcho: true
  GoogleClientSecret:
    Type: String
    Default: ""
    NoEcho: true
  GoogleRefreshToken:
    Type: String
    Default: ""
    NoEcho: true
  HomeAssistantToken:
    Type: String
    Default: ""
    NoEcho: true
  HomeAssistantHost:
    Type: String
    Default: ""
    NoEcho: true
    
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PiAppApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ApiGatewayEndpoint}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  PiAppApiFunction:
    Description: Pi App Lambda Function ARN
    Value: !GetAtt PiAppApiFunction.Arn
  PiAppApiFunctionIamRole:
    Description: Implicit IAM Role created for Pi App function
    Value: !GetAtt PiAppApiFunctionRole.Arn
  Website:
    Value: !GetAtt CloudFrontDistribution.DomainName