env:
  OPEN_WEATHER_API_KEY: ${{secrets.OPEN_WEATHER_API_KEY}}
  OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
  WMATA_API_KEY: ${{secrets.WMATA_API_KEY}}
  GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
  GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
  GOOGLE_REFRESH_TOKEN: ${{secrets.GOOGLE_REFRESH_TOKEN}}
  HOME_ASSISTANT_HOST: ${{secrets.HOME_ASSISTANT_HOST}}
  HOME_ASSISTANT_TOKEN: ${{secrets.HOME_ASSISTANT_TOKEN}}
  PI_NGROK_HOST: ${{secrets.PI_NGROK_HOST}}

on:
  push:
    branches:
      - main
  workflow_dispatch:
    

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_REGION}}
      # sam build 
      - run: sam build 


# sam deploy
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --parameter-overrides OpenWeatherApiKey=${OPEN_WEATHER_API_KEY} OpenAIApiKey=${OPENAI_API_KEY} MetroApiKey=${WMATA_API_KEY} GoogleClientId=${GOOGLE_CLIENT_ID} GoogleClientSecret=${GOOGLE_CLIENT_SECRET}  HomeAssistantToken=${HOME_ASSISTANT_TOKEN} HomeAssistantHost=${HOME_ASSISTANT_HOST} PiNgrokHost=${PI_NGROK_HOST}   \
      - run: npm install --prefix ui
      - run: npm run deploy --prefix ui && aws cloudfront create-invalidation --distribution-id E1CPX8JAUIPVTM --paths "/*"


